### ISSUE TITLE
get_public_ipv4 error

### ISSUE THREAD

**Issue by tvass** [lembregtse/gandi-dyndns#10]
Hello,

http://api.externalip.net/ip/ is out of order since today (1st March).
A nice update could be one additional arg to provide URL.

I have temporarily replace URL with a self hosted PHP : 
<? echo $_SERVER["REMOTE_ADDR"] ?>

**Comment by juanjosepablos** [comment]
I am using:
CURRENT_IP=$(wget -q -O - checkip.dyndns.org|sed -e 's/._Current IP Address: //' -e 's/<._$//')

**Comment by juanjosepablos** [comment]
def get_public_ipv4():
    try:
      data= urllib2.urlopen('http://checkip.dyndns.com/').read()
      matchip = re.search('<body>Current IP Address: (.*?)</body>', data)
      if matchip:
          return matchip.group(1)
    except: pass
    return None

**Comment by juanjosepablos** [comment]
Still, maybe we could request a server for Gandi  that provides that service.

**Comment by soulshake** [comment]
`curl ifconfig.me` works nicely, but I don't know what their policy is on doing it programmatically.
This was also forked by @jasontbradshaw who added a more extensive way of grabbing your IP from various webservices: 
https://github.com/jasontbradshaw/gandi-dyndns/blob/master/gandi_dyndns.py
Otherwise, let me know what you might need from Gandi and I'll see what I can do :)

**Comment by jms301** [comment]
Well having gandi let you set the a record to the IP of the machine it's communicating with would be pretty handy. Since then we won't be relying on a 3rd party site.

**Comment by juanjosepablos** [comment]
ok, lets star by opening thread on their forum. http://groups.gandi.net/en/topic/gandi.en.api/36925

**Comment by soulshake** [comment]
@jms301 That's a good idea. It might have to be rolled into bigger DNS projects later this year, but maybe there's something we can do in the meantime. I'm checking with our devs to see if it's possible.
